name: LousyNet-PlayerCount-Utils
version: '${project.version}'
main: info.charlieward.lousynetplayercountutils.LousyNetPlayerCountUtils
api-version: '1.17'
authors:
  - LousyBoi
commands:
  playerCountReload:
    usage: /playerCountReload
    permission: LousyNetPlayerCountUtils.admin
    description: Reload the config file for LousyNet-PlayerCount-Utils
  playerCountReset:
    usage: /playerCountReset
    permission: LousyNetPlayerCountUtils.admin
    description: Resets the player count in the database
  manualCountChanger:
    usage: /manualCountChanger <Value>
    permission: LousyNetPlayerCountUtils.admin
    description: Manually changes the value sent to the database of the player count
  serverInfo:
    usage: /serverInfo